model:
  base_model: 'roberta-base'

data:
  max_length: 1280
  test_size: 0.1
  seed: 42

lora:
  r: 4
  alpha: 8
  dropout: 0.1
  bias: 'none'
  target_modules: ['key', 'value']

training:
  logging_steps: 100
  learning_rate: 2e-6
  num_epochs: 5
  max_steps: 2000
  train_batch_size: 16
  eval_batch_size: 64
  optimizer: 'adam'
  gradient_checkpointing: False
  weight_decay: 0.01
  dataloader_num_workers: 4
  lr_scheduler_type: 'linear'
  warmup_ratio: 0.1
  eval_strategy: 'steps'

testing:
  batch_size: 64
